

import requests
from flask import Flask, jsonify, request, url_for, render_template
import json
import config
import twitterApi
import translateAPI

app = Flask(__name__)


@app.route('/')
def homepage():
    '''
    Homepage
    '''
    return render_template("index.html")


@app.route('/map', methods=['GET'])
@app.route('/map/', methods=['GET'])

def display_map():
    '''
    At this endpoint we show the full world map via Google maps
    '''
    key = config.MapsAPIKey
    geo = config.googleKeyTranslate
    return render_template("maps.html", key=key, geo=geo)


@app.route('/translated/', methods=['POST'])
def translate():
    text = request.json["tweetText"]
    y = translateAPI.translate(text)
    y = y.decode()
    return y

@app.route('/tweets/<place>', methods=['GET'])
def display_tweet(place):

    country = twitterApi.getPlace(place)
    list = twitterApi.getTheTrendingTweets(country)
    list1 = twitterApi.getTextFromTrending(list)
    tweet = json.dumps(list1, indent=4, sort_keys=True, default=str, ensure_ascii=False)

    return tweet

            
@app.route("/apidocs")
@app.route("/apidocs/")
def swagger():
    '''
    shows documentation for the apidocs, html generated by swagger
    '''
    return render_template("swagger.html")
