# -*- coding: utf-8 -*-

import requests
from flask import Flask, jsonify, request, url_for, render_template
import storage as storage
import json
import config
import urllib.parse


import twitterApi
import translateAPI
#import relevant objects

my_headers = {'Authorization' : 'Bearer ' + config.twitterBearerToken}
trend_world = requests.get('https://api.twitter.com/1.1/trends/available.json', headers=my_headers)
trending_now = trend_world.json()

app = Flask(__name__)


@app.route('/', methods=['GET'])
def homepage():
    '''
    Homepage
    '''
    return render_template("index.html")


@app.route('/places', methods=['GET'])
@app.route('/places/', methods=['GET'])

def display_map():
    '''
    At this endpoint we show the full world map via Google maps
    '''
    key = config.MapsAPIKey
    geo = config.googleKeyTranslate
    return render_template("maps.html", key=key, geo=geo)


@app.route('/translated/', methods=['POST'])
def translate():
    #print(request.data)
    text = request.json["tweetText"]
    #print(text)
    y = translateAPI.translate(text)
    y = y.decode()
    #print(y)
    return y

@app.route('/tweets/', methods=['GET'])
def display_map1():
    data = request.get_json['adress']
    print(request.get_data.body)
    #name = urllib.request.body()
    print("name: ", data)

    country = twitterApi.getPlace(data)
    list = twitterApi.getTheTrendingTweets(country)
    list1 = twitterApi.getTextToTranslate(list)

    tweet = json.dumps(list1, indent=4, sort_keys=True, default=str, ensure_ascii=False)
    
    return tweet

            
@app.route("/apidocs")
@app.route("/apidocs/")
def swagger():
    '''
    shows documentation for the apidocs, html generated by swagger
    '''
    return render_template("swagger.html")
